# Launchable test session configuration file
# See https://docs.launchableinc.com/resources/cli-reference for detailed usage of these options
#  
schema-version: 1.0
build-name: commit_hash
record-build:
  # Put your git repository location here
  source: .
  max_days: 30
record-session:
subset:
  # mode can be subset, subset-and-rest, or record-only
  mode: record-only
  # if mode is subset or subset-and-rest, you must specify one of target/confidence/time
  # examples:
  #   target: 30%  # Create a variable time-based subset of the given percentage. (0%-100%)
  #   confidence: 30%  # Create a confidence-based subset of the given percentage. (0%-100%)
  #   time: 30m  # Create a fixed time-based subset. Select the best set of tests that run within the given time bound. (e.g. 10m for 10 minutes, 2h30m for 2.5 hours, 1w3d for 7+3=10 days. )
  confidence: 99
record-tests:
  # The test results are placed here in JUnit XML format
  result_dir: report
# Set environment variables for Launchable
env:
  LAUNCHABLE_TOKEN: v1:calsoft/pytestdemo:10bde15bec7741909cf8864ccafc5aa8
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1